### ISSUE TITLE
Actualización del Portal SUNAT - Error al registrar el RUC

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#19]
Al ingresar a Ventas > Clientes > Clientes y colocar un RUC y darle enter, me muestra el siguiente error.

![ruc](https://cloud.githubusercontent.com/assets/7632703/24161460/76c407a8-0e32-11e7-87da-9f1be1c805b8.PNG)

Al parecer la imagen **capcha de SUNAT** a cambiado, esto sucede en v7, v8 y v9.
Revisarlo, por favor..!!

**Comment by alexcuellar** [comment]
Se hizo el parche correspondiente.
