### ISSUE TITLE
Desaparición del Botón Contactos

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#20]
Se ha verificado que al ingresar al formulario de Cliente/Proveedores en la pestaña Contactos en la **version 9** no aparece el **_botón de creación de contactos_**

![image](https://cloud.githubusercontent.com/assets/7632703/24172042/cb1e37f2-0e54-11e7-9b36-919801d58f3e.png)

**Se requiere la creación de ese botón en ese formulario, como anteriormente aparecía en la version 8.**
![image](https://cloud.githubusercontent.com/assets/7632703/24172313/c0a78430-0e55-11e7-9614-ff528c2a1423.png)

Cubic ERP Team

**Comment by yurytello** [comment]
Solucionado

![image](https://cloud.githubusercontent.com/assets/7603065/24831013/dddf19d2-1c56-11e7-8844-9bb148ab67b0.png)
