### ISSUE TITLE
BD de plantilla: Error en "viewclass is not a constructor"

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#24]
Al crear las plantillas para las Bases de Datos de Demostración se observa lo siguente:

- Se crea la Base de Datos: template_demostraciones.

![captura_1](https://cloud.githubusercontent.com/assets/7632703/25399871/6ed0d6ee-29b6-11e7-9a26-197e17d50857.PNG)

- Muestra el siguiente mensaje, que no permite que se visualicen los datos ni instalar los módulos.
```
Uncaught TypeError: viewclass is not a constructor.
httos://template_demostraciones.cubicerp.com/web/js/web.assets_backend/778477e:3156
```

![captura_2](https://cloud.githubusercontent.com/assets/7632703/25399875/73ff6ae0-29b6-11e7-897e-527cf91aa5e0.PNG)

**Comment by yurytello** [comment]
crear la base de datos template con otro nombre y luego renombrar la base de datos con el siguiente comando:

psql> ALTER DATABASE name RENAME TO new_name

https://www.postgresql.org/docs/9.1/static/sql-alterdatabase.html
