### ISSUE TITLE
Facturas del TPV no pasan a estado pagado

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#25]
Estimados, 
las facturas generadas a través de las ventas realizadas por el Terminal de Punto Venta, cuando cierro sesión no pasan a estado pagado. 

![1](https://user-images.githubusercontent.com/7632703/28089243-fd0d7d62-664d-11e7-9ca2-6ce88136e3e1.png)

Saludos.

**Comment by lisbethgutierrez** [comment]
Se ha replicado el caso de la empresa Ciudad Bici en la Base de Datos replicada como [tienda_pe.cubicerp.com](tienda_pe.cubicerp.com)

1.- Se ha creado el terminal de Punto de venta
![fp11](https://user-images.githubusercontent.com/7632703/28092804-5585b066-665a-11e7-8fe1-447e5e45bfec.png)
![fp22](https://user-images.githubusercontent.com/7632703/28093243-16e0c7b8-665c-11e7-8740-ce21d944edc5.png)

2.- Se ha creado la sesión
![fp33](https://user-images.githubusercontent.com/7632703/28093289-43f5008e-665c-11e7-9a0c-240bd4f4047c.png)
![fp33](https://user-images.githubusercontent.com/7632703/28093161-b9e84338-665b-11e7-8027-b2e7a2e5a6e1.png)

3.- FACTURA
![fp44](https://user-images.githubusercontent.com/7632703/28092918-c8d3229c-665a-11e7-9501-2fbaffe47982.png)

4.- Balance 0
![balance](https://user-images.githubusercontent.com/7632703/28092934-d0c9a570-665a-11e7-967b-483d6b404f71.png)

Así se muestran todas las facturas creadas desde los pedidos de venta del TPV
![pe1](https://user-images.githubusercontent.com/7632703/28093439-e28fa2f8-665c-11e7-8c43-4b0bee37eadf.png)

**Comment by yurytello** [comment]
se ha creado la opción de Reset Workflow en el workflow de la factura, esto aplica para todos los casos en que el proceso de workflow se queda colgado en estado run
