### ISSUE TITLE
BUG en el Código de Estado de las Notas de Crédito

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#27]
Problemas en las notas de crédito, validadas.

`Código de Estado: El nombre del archivo ZIP es incorrecto`

![zipfacturancnego](https://user-images.githubusercontent.com/7632703/28989757-0cad0d44-793d-11e7-8cb9-6a18c549c35f.png)

**Comment by lisbethgutierrez** [comment]
Se replicó el error, verificando que los clientes creados como empresa si cuentan con RUC pero la casilla de activación de RUC esta deshabilitada.

![vali](https://user-images.githubusercontent.com/7632703/28989827-91b27d94-793d-11e7-9a76-978e50e2fa47.png)

**Comment by alexcuellar** [comment]
La secuencia es incorrecta hay un espacio de mas FN01- 00027 y debería ser FN01-00027 ya se ha corregido la secuencia eliminar la linea del bacth luego cancelar la factura y volverlo a borrador corregir el numero y validarlo nuevamente.
