### ISSUE TITLE
Bug_GyE: no aparece el campo de estructura presupuestal

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#31]
Estimados, 
cuando registro las lineas de mi registro de caja a quienes asigno su estructura presupuestal correspondiente y luego voy a la opción de conciliar y activo la casilla para crear una factura y concilio (OK).
Voy a mis asientos y se han generado 2 asientos, en uno de ellos si me muestra la  estructura presupuestal pero en el otro no.

Su ayuda.

**Comment by lisbethgutierrez** [comment]
Se ha replicado el caso de Gas y Electricidad, quien a la hora de ingresar sus registros de caja (a quienes asigna las estructuras presupuestales correspondientes)
![imgpsh_fullsize_4](https://user-images.githubusercontent.com/7632703/29479552-72a9161e-8438-11e7-9a76-1c38185e57aa.png)

A la hora de conciliar y crear la factura de dicho gasto no muestra ningún campo para asignarle la estructura presupuestal correspondiente.
![imgpsh_fullsize_1](https://user-images.githubusercontent.com/7632703/29479092-df67690c-8435-11e7-8f6e-5167180dcd41.png)

Debido a ello es que después de conciliar el gasto y generarse los asientos uno de ellos muestra la estructura presupestal asignada y el otro no.
![imgpsh_fullsize_2](https://user-images.githubusercontent.com/7632703/29479093-df699d62-8435-11e7-9c04-3142d11b9d12.png)

1. Asiento con la estructura salarial (asiento de la linea registrada en el registo de caja)
![imgpsh_fullsize_5](https://user-images.githubusercontent.com/7632703/29479608-df9ccb44-8438-11e7-8bb4-46c3a83a9983.png)


2. Asiento sin la estructura salarial (asiento generado de la creacion de la factura por medio del check activado a la hora de conciliar el gasto)
![imgpsh_fullsize_3](https://user-images.githubusercontent.com/7632703/29479091-df671466-8435-11e7-9582-53da1c5eba0c.png)

**NOTA:** El cliente requiere que el los dos asientos aparezca la misma estructura Presupuestal.

**Comment by yurytello** [comment]
Fue resuelto en el commit https://github.com/CubicERP/branch/commit/3f74d5d0c2ec0ab84935ae2b00c55b55857331a1 para lo cual deben de instalar el módulo cash_box_budget

Saludos
