### ISSUE TITLE
BUG No regenera la secuencia del reporte 1.2 de forma secuencial

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#34]
Al imprimir el PDF del módulo **l10n_pe_ple01**, **1.2 Detalle de movimiento de cuentas corrientes**, verifica que no jala los datos de los campos: Entidad Financiera, Código Cta. Cte mostrándolos con la denominación desconocido. También, se denota que el numero correlativo no lo esta mostrando de forma secuencial (como debería ser).

![pdf](https://user-images.githubusercontent.com/7632703/30503680-d32e4672-9a30-11e7-83eb-e2c24b4bda0f.png)

Se ha revisado los datos de las cuentas y las Ctas. Bancarias, pero tampoco lo muestra.

Se requiere su ayuda.

**Comment by alexcuellar** [comment]
Resuelto

**Comment by lisbethgutierrez** [comment]
Se ha verificado que efectivamente la secuencia al imprimir el PDF del módulo l10n_pe_ple01, 1.2 Detalle de movimiento de cuentas corrientes, si muestra el correlativo correcto. Pero se aun no muestra los datos de los campos: Entidad Financiera, Código Cta. Cte mostrándolos con la denominación desconocido. 

¿Cuál seria la configuración para que muestre esos dos datos?
