### ISSUE TITLE
BUG al validar las Boletas de Ciudad Bici

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#35]
Estimados al generar la venta 09 Boletas del mes de agosto no permite validarlas:

- `BE01-000270, BE01-000260, BE01-000258, BE01-000244, BE01-000232, BE01-000227, BE01-000188, BE01-000157, BE01-000126.`

Su ayuda.
Vanessa

**Comment by lisbethgutierrez** [comment]
Se ha replicado el BUG presentado por ciudad bici. 
Al generar sus ventas por el POS han quedado 9 boletas en estado borrador, encontrando que casi todas no contaban con el Numero de DNI en el campo doc_number, se ha procedido a colocarles e intentado validarlas pero no cambia de estado, se ha intentado actualizar el flujo pero tampoco cambia de estado. Las boletas a validar son 09 del mes de agosto.

- BE01-000270, BE01-000260, BE01-000258, BE01-000244, BE01-000232, BE01-000227, BE01-000188, BE01-000157, BE01-000126
![cb_2](https://user-images.githubusercontent.com/7632703/30668483-85d6ddf0-9e20-11e7-9b77-135f5a20490d.png)


Equipo cubicERP

**Comment by yurytello** [comment]
Parece que el problema es que los workflow estan en un estado distinto a la factura, según se puede apreciar en la opcion Workflow Instance

![image](https://user-images.githubusercontent.com/7603065/30755152-2f3a5d66-9f8b-11e7-8e5c-5cf04d47e545.png)

La solución pasa por sincronizar manualmente el estado del documento con el estado del "Workflow Instance", editando manualmente el workflow instance y cambiando la actividad actual:

![image](https://user-images.githubusercontent.com/7603065/30755134-195e66f4-9f8b-11e7-9428-4879cdf3eacc.png)
