### ISSUE TITLE
BUG en el cálculo del Total con el del Balance - Negolatina

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#38]
COMO VERAS HAY EN EL REPORTE DE CMPRAS DE EXCEL 
SALE VARIADO UN DECIMAL 
POR EJEMPLO EN LA FACTURA DE COMPRA DE GLORIA

09/2017 | FC-001177 | M001177 | 2017-09-11 | 2017-09-11 | 01 | F582 | 0 | 00005402 | 0 | 6 | 2.01E+10 | GLORIA SA | 1644.62 | 296.03 | 0 | 0 | 0 | 1940.65 |

![image 2](https://user-images.githubusercontent.com/7632703/31296039-8e50105e-aaa6-11e7-9fc9-f00e109763ef.png)
![image 3](https://user-images.githubusercontent.com/7632703/31296065-a3c23624-aaa6-11e7-884d-9df4efaeecfa.png)

**Comment by yurytello** [comment]
Related to the next commit https://github.com/CubicERP/cubicerp/commit/c7840c3f242be61de177b3107f29e3692a101774
