### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by rogeriofalcone** [CubicERP/cubicerp#43]
en el procedimiento INSTALL.md, no se encuentra el vínculo siguiente:
git clone https://github.com/CubicERP/src
me pueden ayudar informando el enlace valido

**Comment by lisbethgutierrez** [comment]
Estimado,
este es el enlace correcto: git clone https://github.com/CubicERP/cubicerp, ingrese al siguiente link donde se encuentra actualizado los pasos: [INSTALL.md](https://github.com/CubicERP/cubicerp/blob/master/INSTALL.md).

Saludos.
