### ISSUE TITLE
BUG en el cálculo de las cotizaciones de venta Negolatina

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#46]
Se ha replicado el Bug presentado por negolatina, al realizar una cotización de ventas. En el cual muestra en la base imponible un monto con una variación de 1 céntimo, al igual en el IGV, es decir que el céntimo que tiene demás el IGV le falta a la base imponible.
![so215](https://user-images.githubusercontent.com/7632703/32966322-74d96f72-cba7-11e7-9475-9487cf34f848.png)

Se ha realizo el cálculo en excel y se obtuvo los montos correctos.
![calculos](https://user-images.githubusercontent.com/7632703/32966459-d4bf033e-cba7-11e7-9bfc-17beb752d2b1.png)

El monto de variación es de un céntimo, lo que es necesario corregir debido a que están teniendo conflictos con sus clientes, por ello.

**Comment by yurytello** [comment]
Solo deben de cambiar el método de cálculo del impuesto de global a lineas en el menú Configuración > Configuración > Contabilidad
![image](https://user-images.githubusercontent.com/7603065/32978734-0f878ce8-cc16-11e7-90a0-3553b8a88a11.png)

SAludos

**Comment by lisbethgutierrez** [comment]
Se ha revisado las pruebas con el método de redondeo del calculo de impuestos: **redondear por linea** con precisión decimal: 4 y el monto total es el que difiere de un céntimo (1,778.24), también se verifico con el  método de redondeo del calculo de impuestos: **redondear globalmente** con precisión decimal: 4  o 2, es el monto total el que difiere en un céntimo (1,778.24), si se encuentra en precisión decimal: 2 y método de redondeo del calculo de impuestos: **redondear por linea**, el monto total es  1,778.25 pero el impuesto con el subtotal difieren en un céntimo  (es decir el céntimo que tiene demás el impuesto, lo debería tener el subtotal), monto que es el que debería salir..
![image](https://user-images.githubusercontent.com/7632703/33040713-ec05938c-ce09-11e7-86a3-991a16d2838d.png)

Recomendaciones a seguir.?
