### ISSUE TITLE
BUG diferencia de 1 céntimo en los pedido realizados por el POS de Negolatina

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#47]
Las cajas están dejando en estado Nuevo algunas Facturas/Boletas, después de haber cambiado el Método de redondeo del cálculo de impuestos a global.
![nego3](https://user-images.githubusercontent.com/7632703/33288632-fce40d88-d38a-11e7-8142-e902b45f00b4.png)
![nego2](https://user-images.githubusercontent.com/7632703/33288633-fd066108-d38a-11e7-9177-122a4655490b.png)
![nego1](https://user-images.githubusercontent.com/7632703/33288634-fd25f77a-d38a-11e7-990d-10cb66774f74.png)

**Comment by lisbethgutierrez** [comment]
Se ha replicado el siguiente BUG presentando por Negolatina, el cual se presenta después de cambiar el Método de redondeo del cálculo de impuestos a global. 
Verificando que ciertas Boletas y Facturas del 26 de noviembre se muestran en los pedidos en estado **NUEVO**, debido a que el terminal de punto de venta ha cobrado un céntimo menos, más o igual al monto peroquedando en el estado antes mencionado, el cual se verifica al ingresar al pedido.
![image](https://user-images.githubusercontent.com/7632703/33292348-eed420f0-d396-11e7-8d1c-7f37abbc3367.png)

Caso de una Factura en estado NUEVO donde se pago de menos:  **13.00 (monto total)**
![image](https://user-images.githubusercontent.com/7632703/33292387-126b2b3a-d397-11e7-9ed7-e1ef5cef323b.png)

Monto Pagado **12.99**
![image](https://user-images.githubusercontent.com/7632703/33292466-562dc666-d397-11e7-9ca4-3903ca754061.png)

Caso de una Boleta en estado NUEVO donde se pago un céntimo de más: **16,62 (monto total)**
![image](https://user-images.githubusercontent.com/7632703/33292662-093ff18e-d398-11e7-8814-4c2c98cee726.png)

Monto pagado **12,63**
![image](https://user-images.githubusercontent.com/7632703/33292684-21976122-d398-11e7-8711-76c25c161bd4.png)


Las Boletas o facturas sin diferencia y que se encuentran en estado NUEVO, se han pagado con el diario utilizado con monto **cero**, pasando luego a estado facturado.

En este momento el Método de redondeo del cálculo de impuestos se encuentra en Redondeo lineal por recomendación de alexander al cliente.

**Comment by yurytello** [comment]
En este caso deberíamos de programar para que el tipo de redondeo se establezca a nivel de factura y/o partner, conversar con el cliente para realizar esta programación.
