### ISSUE TITLE
Liberación de la versión CubicERP V9.2

### ISSUE THREAD

**Issue by luigystoro** [CubicERP/cubicerp#49]
Hace tiempo fue anunciada la liberación de la versión de CubicERP V9.2 la cuál como novedad tenía incorporada la facturación electrónica para Perú. ¿Manejan alguna fecha para la liberación de la misma?, ¿En que repositorio se podría acceder?.

Muchas gracias por su voluntad y colaboración

**Comment by alenguav** [comment]
¿Como sabes la versión que estás descargando por Github?
