### ISSUE TITLE
BUG: Facturas validadas aparecen en la opción de Facturas rectificativas y transacciones de entrada al momento pagarlas

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#51]
Al tratar de pagar una de mis facturas proveedor por medio de la opción CONTABILIDAD / Proveedores / **Pago a Proveedores** y escoger el nombre de la empresa lista las facturas en estado abierto tanto en la posición de **Débitos**  y también en **Facturas rectificativas y transacciones de entrada**.
![pp](https://user-images.githubusercontent.com/7632703/33676056-acafa652-da82-11e7-9ee9-9ef4e5b2cb7f.png)

Negolatina.

**Comment by lisbethgutierrez** [comment]
Se ha replicado el caso presentado por la empresa Negolatina. Ellos intentaron pagar una de sus facturas de proveedor (FP), dándose cuenta que varias de su FP aparecían en la posición de las **Facturas rectificativas y transacciones de entrada**. 

**Caso realizado en nuestro servidor local:**
![pag](https://user-images.githubusercontent.com/7632703/33676865-ea6b78e8-da84-11e7-9962-4fb9b3dc06cb.png)

Se ingreso al asiento contable de una de esas FP que aparece en Facturas rectificativas y transacciones de entrada y se verifico que entre los items del asiento se genera uno de redondeo (**Rounding diff**) en el crédito.
![rounding1](https://user-images.githubusercontent.com/7632703/33676529-f2ba6032-da83-11e7-86eb-6d29e96e6621.png) 

Y el monto de la cuenta **421100** que debería generarse en la opción de cuenta de **crédito** aparece en la opción de débitos. 
![rounding1](https://user-images.githubusercontent.com/7632703/33676990-47c39552-da85-11e7-8add-9c65feb709a4.png)

Verificando que el item de la cuenta 4211 que aparece en débitos debería estar del lado de los créditos y la cuenta de redondeo no debería aparecer, como en el ejemplo de la imagen:
![exce](https://user-images.githubusercontent.com/7632703/33677154-d3c21786-da85-11e7-9012-78a37ad3e0e1.png)

**Comment by alexcuellar** [comment]
Se ha corregido el problema 9e3f0ea
