### ISSUE TITLE
BUG: TPV no termina de cargar

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#56]
Al instalar el modulo terminal Punto de Venta e ingresar a la sesión, no termina de cargar y se queda en la pantalla que se muestra en la imagen:

![image](https://user-images.githubusercontent.com/7632703/34850804-6759666c-f6f5-11e7-86b3-46d6b56f7d55.png)

**Comment by alexcuellar** [comment]
Hay que definir una imagen, al parecer no tenemos definido una imagen o se restauro una base de datos y la imagen no lo encuentra
