### ISSUE TITLE
BUG en el Resumen de Boletas: No se puede leer (parsear) el archivo XML

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#62]
![be](https://user-images.githubusercontent.com/7632703/37530150-f16933ee-2906-11e8-8352-1a6c10cd6281.png)

**Comment by lisbethgutierrez** [comment]
Se replico el bug reportado en la Base de Datos de Ciudad Bici, en el cual se ha generado un batch electrónico del tipo de Resumen de Boletas, se ha listado todas las boletas de un día determinado (ejemplo: 13-03-2018), hecho click en el botón READY, hecho click en el botón Send Request y se ha obtenido como código de estado: **No se puede leer (parsear) el archivo XML** 
![be](https://user-images.githubusercontent.com/7632703/37531656-c67e65ec-290a-11e8-83ff-11e09c3ce620.png)


Verificando que el código de estado obtenido se debe a que uno de los clientes de la boleta no cuenta con DNI y el monto de la boleta es menor a los 700 soles, ya que al completarle el número de DNI al cliente de la(s) boleta(s) y volver a enviar el batch electrónico se corrige el BUG.

**Comment by cubicerpdev** [comment]
El cliente modifico el batch generado y los cambio a resumen diario de boletas. Informar al cliente la correcta generación de los resúmenes diarios
