### ISSUE TITLE
Errores durante la instalación

### ISSUE THREAD

**Issue by alenguav** [CubicERP/cubicerp#63]
El readme debería indicar los prerequisitos necesarios para instalar CubicERP en un servidor Ubuntu limpio. Además debería indicar la versión de Ubuntu recomendada, ya que por ejemplo el comando
sudo pip install suds xmlsec cryptography boxsdk pyDNS cubicerp-client-etl

da el siguiente error en un servidor con Ubuntu 14, recomendando instalar una versión más reciente de Python.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_I343i/xmlsec/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by alenguav** [comment]
Gracias, mi duda saltó porque ayer estuve probando con una imagen de Ubuntu 16 y hoy día probé con Ubuntu 14.
Tengo la impresión de que el manual en español tiene instrucciones diferentes a las del manual en inglés.

**Comment by lisbethgutierrez** [comment]
Son las mismas instrucciones.

Cualquier consulta no dude en hacérmela llegar,
Muchas gracias por su Atención y Comprensión.

*Lisbeth Marilyn Gutiérrez Maza*

*PostVenta y Soporte*

*Correo:* lgutierrez@cubicerp.com

*Consultas:* https://cubicerp.com/help

*Pág. Web: *www.cubicerp.com

*Skype:* cubic.soportefuncional

*Tlf.: *(+51 1) 5362222

*Cel Mvstr:* 940310775
