### ISSUE TITLE
El nombre del archivo ZIP es incorrecto

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#68]
Se ha replicado el bug generado al validar el batch electrónico de una Nota de Crédito Electrónica, obteniendo el siguiente mensaje: 	**El nombre del archivo ZIP es incorrecto**
![image](https://user-images.githubusercontent.com/7632703/38826794-788e3144-4176-11e8-84dc-8d1672448052.png)

**Comment by cubicerpdev** [comment]
Las 
boletas comienzan con el prefijo  BXXX-
facturas comienzan con el prefijo FXXX-

Es posible que por eso te salga el error

**Comment by lisbethgutierrez** [comment]
Se ha corregido el BUG,
Gracias
