### ISSUE TITLE
REPORTE PLE - SUNAT PLE 14.1-Codigo de la Moneda

### ISSUE THREAD

**Issue by yfredes** [CubicERP/cubicerp#75]
AL REPORTEAR EL LIBRO SUNAT PLE 14.1 EN EL EXCEL FALTA AGREGAR LA COLUMA 

 Código  de la Moneda (Tabla 4) | Alfanumérico | 1. Validar con   parámetro tabla 4
EL CUAL ESTA NORMADO , EL TIPO DE CAMBIO ESTA CON  ERRO  TODO APARECE CON 2.5 Y DEVERIA SER 1.00 ( QUE ES NUESTRA MODEDA ) 
ADJUNTO [IMAGEN]
![image](https://user-images.githubusercontent.com/23326810/41182069-bd24fd50-6b39-11e8-8544-c75517048172.png)

**Comment by yurytello** [comment]
En el menú Contabilidad > miselaneos > monedas se puede registrar el código de la moneda según SUNAT
