### ISSUE TITLE
SUNAT PLE 14.1-REDONDEO 

### ISSUE THREAD

**Issue by yfredes** [CubicERP/cubicerp#76]
AL REPORTEAR DEL CUBIC A EXCEL NOS VARIA LOS DATOS ,LOGRANDO ENCONTRAR LOS BUGS EN EL REDONDE EL CUAL LE MOSTRAMOS LA FACTURA NRO  F110-000571 DONDE NO COINCIDE LOS MONTOS AL REPORTEAR
FACTURA F110-000571
![image](https://user-images.githubusercontent.com/23326810/41182254-7b2f5872-6b3a-11e8-9d1e-2b702f67f8ec.png)
BUG EN LOS MONTOS
![image](https://user-images.githubusercontent.com/23326810/41182289-9d30884c-6b3a-11e8-8809-abf190913d6f.png)

**Comment by yurytello** [comment]
Se ha registrado las diferencias de redondeo en la columna de INAFECTOS https://github.com/CubicERP/branch/commit/c287acc0547ac47959719ab219d17fea8d3d4305
