### ISSUE TITLE
BUG Negolatina: El PLE de compras no cuenta con Tabla 30 (casilla 34)

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#78]
PLEN NO  CUENTA  CON ESTA OPCION  DEBE MOSTRARSE DE LA SIGUIENTE MANERA FALTA INPLEMENTAR LA TABLA  30  (CLASIFICACION DE BIENES Y SERVICIOS ADQUIRIDOS CASILLA 34 
![image](https://user-images.githubusercontent.com/7632703/41184265-d42d2db4-6b44-11e8-932e-4022270c125d.png)

> REGISTRÓ DE COMPRAS CON CASILLERO NECESARIOS Y OBLIGATORIOS 

**RECOMENDACIONES** 
![image](https://user-images.githubusercontent.com/7632703/41184306-096b66a8-6b45-11e8-87a4-d19210e4afb9.png)
SE SUGIERE QUE DESGLOSE  
- OPERACIONES GRAVADOS 
- OPERACIONES NOGRAVADAS 
- IGV 
- TOTAL 
![image](https://user-images.githubusercontent.com/7632703/41184335-348f09fc-6b45-11e8-857e-2f88162d34b9.png)

**Comment by yurytello** [comment]
La tabla 30 se configura en el formulario de proveedor

![image](https://user-images.githubusercontent.com/7603065/41324689-9305d5d6-6e7b-11e8-9472-de722b1061e8.png)
