### ISSUE TITLE
Error calculo de impuestos

### ISSUE THREAD

**Issue by martinezint** [CubicERP/cubicerp#80]
hay un error en los cálculos de impuestos.  

si añadimos el isc 30% y marcamos que el impuesto esta añadido en el precio y luego el igv 18%, el calculo final no es correcto, ya que el igv lo calculo desde la base sin el isc.

como solucionarlo. gracias

**Comment by lisbethgutierrez** [comment]
Estimado,
debe configurar de la siguiente manera el código:
![isc_venta](https://user-images.githubusercontent.com/7632703/45571259-4e34fc80-b82b-11e8-84b9-1700acaf5669.png)

![isc_ventacodigo](https://user-images.githubusercontent.com/7632703/45571269-53924700-b82b-11e8-9082-53f10e3a0e52.png)

Ejemplo:
![fact_isc](https://user-images.githubusercontent.com/7632703/45571310-715fac00-b82b-11e8-9446-8e9706bc0749.png)
