### ISSUE TITLE
Bug, Lista de Precios en el POS - Negolatina

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#81]
No esta funcionando la lista de precios en el punto de venta.

**Comment by lisbethgutierrez** [comment]
Se ha reproducido el bug presentando por la empresa negolatina en una base de datos de prueba de CubicERP, creando una lista de precios con un descuento:
![des10](https://user-images.githubusercontent.com/7632703/45980738-70dbc800-c018-11e8-9103-64a1548a03c1.png)

Luego en el POS cuando se selecciona al partner que tiene esa lista de precios entonces el precio en el POS no cambia.
![pos1](https://user-images.githubusercontent.com/7632703/45981274-104d8a80-c01a-11e8-81ca-f76ab66032cc.png)


Caso contrario pasa cuando se realiza la misma operación por la interfaz interna (de una venta directa)
![venta](https://user-images.githubusercontent.com/7632703/45981254-ff047e00-c019-11e8-8c78-77be115e3030.png)

**Comment by lisbethgutierrez** [comment]
Estimado, 
para trabajar los descuentos en la lista de precios, realizar la configuración haciendo uso de la opción: **Nuevo Precio**, como en la imagen, desde **Ventas / Configuración / Tarifas / Tarifas**
![tarifa](https://user-images.githubusercontent.com/7632703/47044073-e2f58780-d154-11e8-955f-1c63ce30ae11.png)

Saludos.

**Comment by cubicerpdev** [comment]
Parchado
