### ISSUE TITLE
BUG: El total sin IGV de los productos facturados en el análisis de facturas no es correcto

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#83]
Tengo una consulta. Me están pidiendo que realice un informe de los productos que mas se venden de cada marca, pero a la hora de sacar el infome me salen algunas incongruencias.

La ruta por la que voy es la siguiente: Informes - Analisis de facturas
- Elimino "Periodo" del filtro porque necesitamos un monto general.
- De "Medidas" agrego: # de facturas.
- Y en Cinelli pongo "+" y seleccione Producto.

Aqui es cuando nos mareamos, ya que salen algunos productos así:
![image](https://user-images.githubusercontent.com/7632703/48788994-fba80e80-ecb9-11e8-86b3-e35e67d02a74.png) ![image](https://user-images.githubusercontent.com/7632703/48789034-12e6fc00-ecba-11e8-9b72-8597bbf0faa9.png)

El total sin impuestos es muy elevado y el numero de facturas son dos.

Y la realidad es que solo hay 1 factura por ese producto y el monto de venta es el correcto.
Por qué varían los datos? cómo puedo arreglarlo u obtener la información correcta?

Mil gracias por tu apoyo.

**Comment by lisbethgutierrez** [comment]
Se ha replicado el caso y al realizar el análisis de los productos de las marcas más vendidas en la base de datos de ciudad bici, se ha detectado que los datos estadísticos de algunos productos no son congruentes.
![cb1](https://user-images.githubusercontent.com/7632703/48789237-9b659c80-ecba-11e8-875c-c697968459e6.JPG)

Al realizar el análisis con el producto: [AMGRA090] Codo - Cinelli - Graphis 31.8 90, con cantidad 2, la cantidad total sin impuestos es de 33738.86.

Cuando al realizar el análisis por medio del producto difiere la cantidad. Sub Total (sin IGV): 229.74
![cb2](https://user-images.githubusercontent.com/7632703/48789264-a4566e00-ecba-11e8-9223-a87eb9f3105c.JPG)

El mismo caso pasa en el producto: [NMGELRS] Cinta de Manillar - Cinelli - Cork Gel Red / rojo bar tape, con monto (sin IGV): 435.58
![cb3](https://user-images.githubusercontent.com/7632703/48789277-aa4c4f00-ecba-11e8-9d2d-e040d764ed79.JPG)

Cuando al realizar el análisis por medio del producto difiere la cantidad. Sub Total (sin IGV): 208.47
![cb4](https://user-images.githubusercontent.com/7632703/48789285-afa99980-ecba-11e8-8231-43d0530b0e8a.JPG)

**Comment by yurytello** [comment]
Fixed
